// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ContosoUniversity.Web.Automation.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("_Example_")]
    [NUnit.Framework.IgnoreAttribute()]
    public partial class _Example_Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "_Examples.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "_Example_", "", ProgrammingLanguage.CSharp, new string[] {
                        "ignore"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Example steps for setting up test data in the database")]
        public virtual void ExampleStepsForSettingUpTestDataInTheDatabase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Example steps for setting up test data in the database", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Budget",
                        "StartDate"});
            table1.AddRow(new string[] {
                        "MyDepartment",
                        "123.1",
                        "01-Oct-2010"});
            table1.AddRow(new string[] {
                        "XDepartment",
                        "12.1",
                        "01-Oct-2020"});
            table1.AddRow(new string[] {
                        "BobDepartment",
                        "23.1",
                        "01-Oct-2030"});
            table1.AddRow(new string[] {
                        "JKDepartment",
                        "13323.1",
                        "01-Oct-2040"});
#line 12
 testRunner.Given("I have the following departments", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "LastName",
                        "FirstMidName",
                        "EnrollmentDate"});
            table2.AddRow(new string[] {
                        "Smith",
                        "Tod",
                        "01-Oct-2010"});
            table2.AddRow(new string[] {
                        "Tod",
                        "Sweeney",
                        "01-Oct-2010"});
            table2.AddRow(new string[] {
                        "Jones",
                        "Jimbo",
                        "01-Oct-2010"});
#line 20
 testRunner.And("I have the following students", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "CourseID",
                        "Title",
                        "Credits",
                        "Department Name"});
            table3.AddRow(new string[] {
                        "100",
                        "My Course",
                        "1",
                        "MyDepartment"});
            table3.AddRow(new string[] {
                        "101",
                        "Your Course",
                        "1",
                        "MyDepartment"});
            table3.AddRow(new string[] {
                        "102",
                        "Jims Course",
                        "1",
                        "XDepartment"});
            table3.AddRow(new string[] {
                        "103",
                        "Bobs Course",
                        "1",
                        "BobDepartment"});
#line 27
 testRunner.And("I have the following courses", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "LastName",
                        "FirstMidName",
                        "HireDate",
                        "OfficeLocation",
                        "Selected Courses"});
            table4.AddRow(new string[] {
                        "Lemmon",
                        "Keith",
                        "01-Oct-2010",
                        "Bath",
                        "Bobs Course ,Jims Course"});
            table4.AddRow(new string[] {
                        "Cox",
                        "John",
                        "01-Oct-2010",
                        "Bath",
                        "Bobs Course ,Jims Course, My Course"});
            table4.AddRow(new string[] {
                        "Burges",
                        "Arthur",
                        "01-Oct-2010",
                        "London",
                        "Bobs Course ,Jims Course"});
            table4.AddRow(new string[] {
                        "Osborne",
                        "Fred",
                        "01-Oct-2010",
                        "Brighton",
                        "Your Course"});
#line 35
 testRunner.And("I have the following instructors", ((string)(null)), table4, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Example steps")]
        public virtual void ExampleSteps()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Example steps", ((string[])(null)));
#line 48
this.ScenarioSetup(scenarioInfo);
#line 51
 testRunner.Given("I\'m at at the \"Instructor\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
 testRunner.When("I select the \"Create New\" link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
 testRunner.And("I press the \"Create\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("I select the \"Edit\" link on the \"students\" table on row \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyId",
                        "Value"});
            table5.AddRow(new string[] {
                        "Title",
                        "Your title"});
#line 59
 testRunner.And("I enter the following details", ((string)(null)), table5, "And ");
#line 64
 testRunner.Then("I expect the \"students\" table to be empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Row",
                        "Column1",
                        "Column2",
                        "Column3",
                        "Column4",
                        "Column5"});
            table6.AddRow(new string[] {
                        "1",
                        "1234",
                        "Course Title",
                        "1",
                        "XDepartment",
                        "Edit ! Details ! Delete"});
#line 65
 testRunner.And("I expect the following info displayed in the \"students\" table", ((string)(null)), table6, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
