// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ContosoUniversity.Web.Automation.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("DataSetup")]
    public partial class DataSetupFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DataSetup.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DataSetup", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Example steps for setting up test data in the database")]
        public virtual void ExampleStepsForSettingUpTestDataInTheDatabase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Example steps for setting up test data in the database", ((string[])(null)));
#line 8
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Budget",
                        "StartDate"});
            table1.AddRow(new string[] {
                        "MyDepartment",
                        "123.1",
                        "01-Oct-2010"});
            table1.AddRow(new string[] {
                        "XDepartment",
                        "12.1",
                        "01-Oct-2020"});
            table1.AddRow(new string[] {
                        "BobDepartment",
                        "23.1",
                        "01-Oct-2030"});
            table1.AddRow(new string[] {
                        "JKDepartment",
                        "13323.1",
                        "01-Oct-2040"});
            table1.AddRow(new string[] {
                        "Mums Department",
                        "123.1",
                        "01-Oct-2040"});
#line 11
 testRunner.Given("I have the following departments", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "LastName",
                        "FirstMidName",
                        "EnrollmentDate"});
            table2.AddRow(new string[] {
                        "Smith",
                        "Tod",
                        "01-Oct-2010"});
            table2.AddRow(new string[] {
                        "Tod",
                        "Sweeney",
                        "01-Oct-2010"});
            table2.AddRow(new string[] {
                        "Jones",
                        "Jimbo",
                        "01-Oct-2010"});
#line 20
 testRunner.And("I have the following students", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "CourseID",
                        "Title",
                        "Credits",
                        "Department Name"});
            table3.AddRow(new string[] {
                        "100",
                        "My Course",
                        "1",
                        "MyDepartment"});
            table3.AddRow(new string[] {
                        "101",
                        "Your Course",
                        "1",
                        "MyDepartment"});
            table3.AddRow(new string[] {
                        "102",
                        "Jims Course",
                        "1",
                        "XDepartment"});
            table3.AddRow(new string[] {
                        "103",
                        "Bobs Course",
                        "1",
                        "BobDepartment"});
#line 27
 testRunner.And("I have the following courses", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "LastName",
                        "FirstMidName",
                        "HireDate",
                        "OfficeLocation",
                        "Selected Courses"});
            table4.AddRow(new string[] {
                        "Lemmon",
                        "Keith",
                        "01-Oct-2010",
                        "Bath",
                        "Bobs Course ,Jims Course"});
            table4.AddRow(new string[] {
                        "Cox",
                        "John",
                        "01-Oct-2010",
                        "Bath",
                        "Bobs Course ,Jims Course, My Course"});
            table4.AddRow(new string[] {
                        "Burges",
                        "Arthur",
                        "01-Oct-2010",
                        "London",
                        "Bobs Course ,Jims Course"});
            table4.AddRow(new string[] {
                        "Osborne",
                        "Fred",
                        "01-Oct-2010",
                        "Brighton",
                        "Your Course"});
#line 35
 testRunner.And("I have the following instructors", ((string)(null)), table4, "And ");
#line 42
 testRunner.When("I\'m at at the \"Course\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.Then("I expect the \"courses\" table to contain \"4\" rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 45
 testRunner.And("I\'m at at the \"Student\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And("I expect the \"students\" table to contain \"3\" rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.When("I\'m at at the \"Instructor\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
 testRunner.Then("I expect the \"instructors\" table to contain \"4\" rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 51
 testRunner.When("I\'m at at the \"Department\" page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.Then("I expect the \"departments\" table to contain \"5\" rows", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
